#!/bin/bash
# this script copies H5 files generated by Batch H5 generators to the tape storage
# usage: ./H5toTAPE.sh PATH_TO_H5_FILES PATH_TO_TAPES
# For example, ./H5toTape.sh /work/gorkhover/subdir /UserData/gorkhover/subdir
H5DIR=$1
TAPEDIR=$2

for f in $H5DIR/*.h5
do
	filename="${f##*/}"
	runnum="${filename%*'.h5'}"
	qsub -o $H5DIR/logs/tapes_$runnum.out -e $H5DIR/logs/tapes_$runnum.error -N T$runnum -v TAPEDIR=$TAPEDIR,FILE=$f singleCopy2Tape.sh
	wait
done
