#!/bin/bash
# Generates the H5 files using the tag lists generated by MakeTagsBatchLoop.sh
# usage: ./MakeH5BatchLoop.sh runnumber_start number_of_runs_to_convert
# Updates lines below !!!UPDATE ME!!!

# The initial runnumber to convert and the number of runs to convert are read from the command line
loop=$2
run=$1
run0=$run
counter="0"

# !!!UPDATE ME!!! - Specifies beamline to convert to H5
beamline="3"

# !!!UPDATE ME!!! - Specifies directory to save H5s to AND the configuration file specifying detectors to save
H5DIR="/work/gorkhover/H5/TAIS2019"
CONFFILE="/home/gorkhover/TAIS2019/Conf_List/RunData2019_TaisGorkhover.conf"

# Check if H5dir and configuration file exist. If not, exit to user.
if [ ! -d "$H5DIR" ]; then
	echo "Specified directory for saving H5 files does not exist. Exiting."
	return
fi

if [ ! -f "$CONFFILE" ]; then
	echo "Specified configuration file does not exist. Exiting."
	return
fi


# Check if subdirectories below H5DIR exist. If not, create them.
if [ ! -d "$H5DIR/Tags" ]; then
	mkdir "$H5DIR/Tags"
fi

if [ ! -d "$H5DIR/logs" ]; then
	mkdir "$H5DIR/logs"
fi

# For each runnumber, generate the H5 using the tag list at Tags/tag_RUNNUMBER.lst
counter="0"
run=$run0
while [[ $counter -lt $loop ]]
do
	echo "Run Number is" $run
	rm $H5DIR/$run.h5

	qsub -o $H5DIR/logs/h5_$run.out -e $H5DIR/logs/h5_$run.error -N R$run -v RUN=$run,H5DIR=$H5DIR,CONFFILE=$CONFFILE singleGrab.sh

	((counter++))
	((run++))
	wait
done
